name: libsqlite3_turso
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.3.1

dependencies:
  drift: ^2.28.1
  sqlite3: ^2.9.0

dev_dependencies:
  build_runner: ^2.6.1
  drift_dev: ^2.28.1
  lints: ^3.0.0
  test: ^1.25.8
