name: Build LibSqlite_Turso Shared Library

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build LibSqlite_Turso
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build
          cargo build --release --all-features



      - name: Find built shared library
        id: find_artifact
        shell: bash
        run: |
          DEBUG_SO=target/debug/libsqlite3.so
          RELEASE_SO=target/release/libsqlite3.so

          if [[ ! -f "$DEBUG_SO" ]]; then
            echo "Debug shared library not found at $DEBUG_SO"
            exit 1
          fi

          if [[ ! -f "$RELEASE_SO" ]]; then
            echo "Release shared library not found at $RELEASE_SO"
            exit 1
          fi

          DEBUG_NAME=target/debug/libsqlite3-debug.so
          RELEASE_NAME=target/release/libsqlite3-release.so

          mv "$DEBUG_SO" "$DEBUG_NAME"
          mv "$RELEASE_SO" "$RELEASE_NAME"

          echo "DEBUG_ARTIFACT=$DEBUG_NAME" >> $GITHUB_ENV
          echo "RELEASE_ARTIFACT=$RELEASE_NAME" >> $GITHUB_ENV
          
      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsqlite3-debug
          path: ${{ env.DEBUG_ARTIFACT }}

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsqlite3-release
          path: ${{ env.RELEASE_ARTIFACT }}